"use client";
import {useState} from "react";
import {AnimatePresence,motion} from "framer-motion";
import {Apple,ArrowLeft,ArrowUpRight,Calendar,ChevronRight,Heart,Home,Phone,RotateCw,Search,Smartphone,UserRound,Users,Wallet,X,Zap,MapPin,MoreHorizontal,Bell,Plus,CheckCircle2,Clock3} from "lucide-react";

type OS="ios"|"android"; type Screen="home"|"leads"|"lead"|"calls"|"profile"|"estate"|"wallet";
const leads=[
{name:"Rahul Sharma",company:"Northstar Labs",status:"Hot",value:"₹4.2L",color:"from-orange-400 to-pink-500"},
{name:"Priya Reddy",company:"Vertex Systems",status:"Warm",value:"₹2.8L",color:"from-violet-400 to-blue-500"},
{name:"Amit Kumar",company:"FinEdge",status:"New",value:"₹1.5L",color:"from-cyan-400 to-emerald-500"}
];

export default function Page(){
 const[os,setOs]=useState<OS>("ios"),[device,setDevice]=useState("iPhone 16 Pro"),[land,setLand]=useState(false),[screen,setScreen]=useState<Screen>("home"),[lead,setLead]=useState(leads[0]),[toast,setToast]=useState("");
 const android=os==="android";
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1900)};
 return <main className="min-h-screen bg-[#f4f7fb]">
  <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><b className="flex items-center gap-2 text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-600 to-blue-500 text-white"><Smartphone size={18}/></span>Nexora Mobile</b><span className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-600">Interactive simulator</span></nav>
  <section className="grid-bg mx-4 rounded-[34px] border border-slate-200 bg-white/60 px-5 py-12 md:py-16"><div className="mx-auto max-w-7xl">
   <p className="text-xs font-black uppercase tracking-[.25em] text-violet-600">Flutter-style mobile product showcase</p>
   <h1 className="mt-3 text-5xl font-black tracking-tight text-slate-900 md:text-7xl">Beautiful apps.<br/><span className="bg-gradient-to-r from-violet-600 via-blue-500 to-cyan-400 bg-clip-text text-transparent">Real interactions.</span></h1>
   <p className="mt-5 max-w-2xl text-base leading-7 text-slate-600">Switch between iOS and Android, choose a device, rotate it and interact with a colorful Material-inspired application directly in the browser.</p>
   <div className="mt-10 grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
    <div>
     <div className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-wrap gap-2">
      <button onClick={()=>{setOs("ios");setDevice("iPhone 16 Pro")}} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${!android?"bg-gradient-to-r from-violet-600 to-blue-500 text-white shadow-lg shadow-violet-200":"bg-slate-100 text-slate-700"}`}><Apple size={16}/> iOS</button>
      <button onClick={()=>{setOs("android");setDevice("Pixel 9 Pro")}} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${android?"bg-gradient-to-r from-violet-600 to-blue-500 text-white shadow-lg shadow-violet-200":"bg-slate-100 text-slate-700"}`}><Smartphone size={16}/> Android</button>
      <button onClick={()=>setLand(!land)} className="ml-auto flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-bold text-slate-700"><RotateCw size={16}/> Rotate</button>
     </div><div className="mt-3 flex flex-wrap gap-2">{(android?["Pixel 9 Pro","Pixel 9","Galaxy S25"]:["iPhone 16 Pro","iPhone 16","iPhone SE"]).map(x=><button key={x} onClick={()=>setDevice(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${device===x?"bg-slate-900 text-white":"bg-slate-100 text-slate-600"}`}>{x}</button>)}</div></div>
     <div className="mt-5 grid grid-cols-2 gap-3">{[["Material-inspired","Rich color system"],["Responsive","Portrait + landscape"],["Interactive","Real React screens"],["API-ready","Backend later"]].map(x=><div key={x[0]} className="rounded-2xl border border-slate-200 bg-white p-4"><b className="text-sm text-slate-800">{x[0]}</b><p className="mt-1 text-xs text-slate-500">{x[1]}</p></div>)}</div>
    </div>
    <div className="flex min-h-[780px] items-center justify-center overflow-auto rounded-[40px] border border-slate-200 bg-gradient-to-br from-violet-50 via-blue-50 to-cyan-50 p-8"><Device os={os} device={device} land={land} screen={screen} setScreen={setScreen} lead={lead} setLead={setLead} notify={notify}/></div>
   </div>
  </div></section>
  <section className="mx-auto max-w-7xl px-5 py-16"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">What this demonstrates</p><div className="mt-5 grid gap-4 md:grid-cols-4">{["Mobile UX & navigation","Forms & state management","Cross-platform product UI","API-ready architecture"].map((x,i)=><div key={x} className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-2xl font-black text-violet-600">0{i+1}</p><h3 className="mt-8 font-bold text-slate-800">{x}</h3><p className="mt-2 text-xs leading-5 text-slate-500">A working frontend prototype designed for real API integration later.</p></div>)}</div></section>
  {toast&&<div className="fixed bottom-5 right-5 z-50 rounded-2xl bg-slate-900 px-4 py-3 text-xs font-bold text-white shadow-xl">{toast}</div>}
 </main>
}

function Device({os,device,land,screen,setScreen,lead,setLead,notify}:{os:OS;device:string;land:boolean;screen:Screen;setScreen:(s:Screen)=>void;lead:any;setLead:(x:any)=>void;notify:(s:string)=>void}){
 const[w,h]=land?[820,390]:[390,820],android=os==="android";
 return <motion.div layout style={{width:w,height:h}} className={`phone shrink-0 overflow-hidden bg-white ${android?"rounded-[40px] border-[8px] border-slate-800":"rounded-[50px] border-[10px] border-slate-900"}`}>
  <div className="relative h-full overflow-hidden rounded-[40px] bg-[#f8faff]"><div className={`absolute left-1/2 top-2 z-30 -translate-x-1/2 rounded-full bg-slate-950 ${android?"h-5 w-20":"h-7 w-28"}`}/>
   <div className="h-full overflow-y-auto no-scrollbar"><div className="flex justify-between px-6 pb-3 pt-9 text-[10px] font-bold text-slate-700"><span>9:41</span><span>{android?"5G  ▰":"● ● ▰"}</span></div>
    <AnimatePresence mode="wait"><motion.div key={screen} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.22}} className="pb-5">
     {screen==="home"&&<HomeScreen set={setScreen}/>}
     {screen==="leads"&&<Leads set={setScreen} select={x=>{setLead(x);setScreen("lead")}}/>}
     {screen==="lead"&&<Lead lead={lead} set={setScreen} notify={notify}/>}
     {screen==="calls"&&<Calls set={setScreen} notify={notify}/>}
     {screen==="profile"&&<Profile set={setScreen}/>}
     {screen==="estate"&&<Estate set={setScreen} notify={notify}/>}
     {screen==="wallet"&&<WalletScreen set={setScreen}/>}
    </motion.div></AnimatePresence>
   </div>
  </div>
 </motion.div>
}

function HomeScreen({set}:{set:(s:Screen)=>void}){
 return <div className="px-5"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500">Good morning</p><h2 className="mt-1 text-2xl font-black text-slate-900">Harsh 👋</h2></div><button className="relative grid h-10 w-10 place-items-center rounded-full bg-white shadow-sm"><Bell size={17} className="text-slate-700"/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-pink-500"/></button></div>
  <div className="mt-5 overflow-hidden rounded-[28px] bg-gradient-to-br from-violet-600 via-blue-600 to-cyan-500 p-5 text-white shadow-xl shadow-blue-100"><div className="flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-widest text-white/70">Portfolio revenue</p><ArrowUpRight size={18}/></div><p className="mt-2 text-3xl font-black">₹18.4L</p><p className="mt-1 text-[10px] text-white/70">+18.4% from last month</p><div className="mt-5 flex h-12 items-end gap-1">{[28,44,38,60,52,78,67,92].map((v,i)=><i key={i} className="flex-1 rounded-t bg-white/70" style={{height:`${v}%`}}/>)}</div></div>
  <div className="mt-5 grid grid-cols-2 gap-3">{[[Users,"Leads","leads","from-orange-400 to-pink-500"],[Phone,"Calls","calls","from-blue-500 to-cyan-400"],[Home,"Estate","estate","from-emerald-400 to-teal-500"],[Wallet,"Wallet","wallet","from-amber-400 to-orange-500"]].map(([I,n,s,c])=><button key={String(n)} onClick={()=>set(s as Screen)} className="group rounded-3xl bg-white p-4 text-left shadow-sm ring-1 ring-slate-100 active:scale-95"><span className={`grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br ${String(c)} text-white shadow-md`}><I size={18}/></span><b className="mt-4 block text-sm text-slate-800">{String(n)}</b><span className="mt-1 block text-[9px] text-slate-400">Tap to explore</span></button>)}</div>
  <div className="mt-4 rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-100"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-100 text-violet-600"><Calendar size={15}/></span><div><b className="text-xs">Next follow-up</b><p className="text-[9px] text-slate-400">Today · 4:30 PM</p></div><ChevronRight className="ml-auto text-slate-300" size={16}/></div><p className="mt-3 text-sm font-black">Rahul Sharma</p><p className="text-[9px] text-slate-500">3 BHK enquiry · High intent</p></div><Bottom set={set}/></div>
}

function Leads({set,select}:{set:(s:Screen)=>void;select:(x:any)=>void}){
 return <div className="px-5"><Top title="Leads" back={()=>set("home")} badge="24"/><div className="mt-4 flex gap-2 rounded-2xl bg-slate-100 p-3 text-slate-400"><Search size={14}/><span className="text-[10px]">Search leads...</span></div><div className="mt-4 space-y-2">{leads.map(x=><button key={x.name} onClick={()=>select(x)} className="flex w-full items-center gap-3 rounded-3xl bg-white p-3 text-left shadow-sm ring-1 ring-slate-100"><span className={`grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br ${x.color} text-white`}><UserRound size={15}/></span><span className="flex-1"><b className="block text-xs text-slate-800">{x.name}</b><small className="text-[9px] text-slate-400">{x.company}</small></span><span className="text-right"><small className="rounded-full bg-orange-50 px-2 py-1 text-[8px] font-bold text-orange-600">{x.status}</small><small className="mt-1 block text-[9px] font-bold text-slate-700">{x.value}</small></span></button>)}</div><Bottom set={set}/></div>
}

function Top({title,back,badge}:{title:string;back:()=>void;badge?:string}){return <div className="flex items-center gap-2"><button onClick={back} className="grid h-9 w-9 place-items-center rounded-xl bg-white shadow-sm"><ArrowLeft size={17}/></button><h2 className="text-xl font-black text-slate-900">{title}</h2>{badge&&<span className="ml-auto rounded-full bg-violet-100 px-2 py-1 text-[9px] font-bold text-violet-600">{badge}</span>}</div>}

function Lead({lead,set,notify}:{lead:any;set:(s:Screen)=>void;notify:(s:string)=>void}){return <div className="px-5"><Top title="Lead details" back={()=>set("leads")}/><div className="mt-6 rounded-[28px] bg-gradient-to-br from-violet-600 to-blue-500 p-5 text-center text-white"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-white/20"><UserRound/></div><h3 className="mt-3 text-lg font-black">{lead.name}</h3><p className="text-[10px] text-white/70">{lead.company}</p></div><div className="mt-4 grid grid-cols-2 gap-2">{[["Status",lead.status],["Value",lead.value],["Interest","High"],["Follow-up","Today"]].map(x=><div key={x[0]} className="rounded-2xl bg-white p-3 shadow-sm"><small className="text-[9px] text-slate-400">{x[0]}</small><b className="mt-1 block text-xs text-slate-800">{x[1]}</b></div>)}</div><button onClick={()=>notify("Demo call started")} className="mt-4 flex w-full justify-center gap-2 rounded-2xl bg-slate-900 py-3.5 text-xs font-black text-white"><Phone size={14}/> Call lead</button><button onClick={()=>notify("Follow-up scheduled")} className="mt-2 flex w-full justify-center gap-2 rounded-2xl bg-violet-100 py-3.5 text-xs font-black text-violet-700"><Calendar size={14}/> Schedule follow-up</button><div className="mt-4 rounded-2xl bg-amber-50 p-4 text-[10px] leading-5 text-amber-800"><b>AI note</b><br/>Interested in a 3 BHK. Budget ₹1.2–1.5 Cr. Wants a site visit this weekend.</div></div>}

function Calls({set,notify}:{set:(s:Screen)=>void;notify:(s:string)=>void}){return <div className="px-5"><Top title="AI Calls" back={()=>set("home")} badge="LIVE"/><div className="mt-5 rounded-[30px] bg-gradient-to-br from-blue-600 to-cyan-500 p-5 text-white shadow-lg shadow-blue-100"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-widest text-white/70">AI calling</p><p className="mt-1 text-3xl font-black">148</p><p className="text-[10px] text-white/70">calls today</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/20"><Phone size={22}/></span></div><button onClick={()=>notify("Demo call connected")} className="mt-5 w-full rounded-2xl bg-white py-3 text-xs font-black text-blue-700">Start demo call</button></div><div className="mt-4 space-y-2">{leads.slice(0,2).map(x=><div key={x.name} className="flex items-center gap-3 rounded-3xl bg-white p-3 shadow-sm"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/><div className="flex-1"><b className="text-xs">{x.name}</b><p className="text-[9px] text-slate-400">Interested · 01:24</p></div><MoreHorizontal size={16} className="text-slate-400"/></div>)}</div></div>}

function Profile({set}:{set:(s:Screen)=>void}){return <div className="px-5"><Top title="Profile" back={()=>set("home")}/><div className="mt-6 rounded-[30px] bg-gradient-to-br from-fuchsia-500 to-violet-600 p-6 text-center text-white"><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-white/20 text-xl font-black">HA</div><h3 className="mt-3 text-lg font-black">Harsh Aryan</h3><p className="text-[10px] text-white/70">Product workspace</p></div><div className="mt-4 space-y-2">{["Personal information","Notifications","Security","Preferences"].map((x,i)=><button key={x} className="flex w-full items-center justify-between rounded-2xl bg-white p-4 text-xs font-bold shadow-sm">{x}<ChevronRight size={14} className="text-slate-300"/></button>)}</div></div>}

function Estate({set,notify}:{set:(s:Screen)=>void;notify:(s:string)=>void}){return <div className="px-5"><Top title="Nexora Estate" back={()=>set("home")}/><div className="mt-5 rounded-[30px] bg-gradient-to-br from-emerald-500 to-teal-500 p-5 text-white shadow-lg"><p className="text-[9px] font-bold uppercase tracking-widest text-white/70">Find your next home</p><h3 className="mt-2 text-2xl font-black">Properties that fit.</h3><div className="mt-4 flex items-center gap-2 rounded-2xl bg-white/15 p-3 text-[10px]"><MapPin size={13}/> Tellapur · 3 BHK · ₹1–1.5 Cr</div><button onClick={()=>notify("3 properties found")} className="mt-3 w-full rounded-2xl bg-white py-3 text-xs font-black text-emerald-700">Search properties</button></div><div className="mt-4 overflow-hidden rounded-[28px] bg-white shadow-sm"><div className="h-24 bg-gradient-to-br from-slate-200 via-blue-100 to-emerald-100"/><div className="p-4"><div className="flex justify-between"><b className="text-xs">Premium 3 BHK Residence</b><button onClick={()=>notify("Added to shortlist")}><Heart size={16} className="text-rose-500"/></button></div><p className="mt-1 text-[10px] text-slate-500">Tellapur · 1,850 sq.ft · ₹1.28 Cr</p><div className="mt-3 flex gap-2 text-[8px]"><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-600">RERA verified</span><span className="rounded-full bg-violet-50 px-2 py-1 text-violet-600">High demand</span></div></div></div></div>}

function WalletScreen({set}:{set:(s:Screen)=>void}){return <div className="px-5"><Top title="Wallet" back={()=>set("home")}/><div className="mt-5 rounded-[30px] bg-gradient-to-br from-amber-400 to-orange-500 p-5 text-white"><p className="text-[9px] uppercase tracking-widest text-white/70">Available balance</p><p className="mt-2 text-3xl font-black">₹42,680</p><div className="mt-5 flex justify-between text-[10px]"><span>+ ₹12,400 this month</span><span>**** 4821</span></div></div><div className="mt-4 rounded-3xl bg-white p-4 shadow-sm"><b className="text-xs">Recent activity</b>{["Client payment · +₹8,500","Subscription · -₹799","Bonus · +₹2,400"].map(x=><div key={x} className="mt-3 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-xl bg-amber-50 text-amber-600"><Wallet size={14}/></span><span className="text-[10px] font-bold">{x}</span></div>)}</div></div>}

function Bottom({set}:{set:(s:Screen)=>void}){return <div className="mt-8 flex items-center justify-around rounded-[24px] bg-white p-2 shadow-lg shadow-slate-100">{[[Home,"Home","home"],[Users,"Leads","leads"],[Phone,"Calls","calls"],[UserRound,"Me","profile"]].map(([I,n,s])=><button key={String(n)} onClick={()=>set(s as Screen)} className="flex min-w-12 flex-col items-center gap-1 rounded-2xl px-3 py-2 text-[8px] font-bold text-slate-500 hover:bg-violet-50 hover:text-violet-600"><I size={16}/>{String(n)}</button>)}</div>}
